recordmanager-ui/src/main/java/pro/deta/detatrak/user/form/GenericCodeForm.java
package pro.deta.detatrak.user.form;

import java.util.List;

import org.apache.struts.action.ActionForm;

import ru.yar.vi.rm.data.GenCodeDO;

public class GenericCodeForm extends ActionForm  {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7753207069705827532L;
	private String genType;
	private String genCode;
	private String arrayName;
	private List<GenCodeDO> list = null;
	
	public String getGenType() {
		return genType;
	}
	public void setGenType(String genType) {
		this.genType = genType;
	}
	public String getGenCode() {
		return genCode;
	}
	public void setGenCode(String genCode) {
		this.genCode = genCode;
	}
	public String getArrayName() {
		return arrayName;
	}
	public void setArrayName(String arrayName) {
		this.arrayName = arrayName;
	}
	public List<GenCodeDO> getList() {
		return list;
	}
	public void setList(List<GenCodeDO> list) {
		this.list = list;
	}
	
	public String getName() {
		if(arrayName != null && !"".equalsIgnoreCase(arrayName))
			return arrayName;
		else 
			return genType;
	}

}

recordmanager-ui/src/main/webapp/tiles/base.jsp
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><%
response.setHeader("Cache-Control","no-cache"); 
response.setHeader("Pragma","no-cache"); 
response.setDateHeader ("Expires", -1);
%>
<%@page session="true" contentType="text/html; charset=windows-1251" %>
<%@ taglib uri="http://struts.apache.org/tags-tiles" prefix="t" %>

<t:insert attribute="begin" flush="false"/>

<t:insert attribute="body" flush="false"/>

<t:insert attribute="end" flush="false"/>

recordmanager-ui/src/main/webapp/tiles/gencode.jsp
<%@page contentType="text/javascript" trimDirectiveWhitespaces="true"%>
<%response.setHeader("Cache-Control", "max-age=3600, must-revalidate");%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
var <c:out value="${GenericCodeForm.name}"/>_List = [
<c:forEach items="${GenericCodeForm.list }" var="item" varStatus="st">{id: "<c:out value="${item.id }"/>", name: "<c:out value="${item.genDesc }"/>"}<c:if test="${not st.last}">,</c:if>
</c:forEach>
];

var <c:out value="${GenericCodeForm.name}"/>AutocompleteValues = [];

for(var i = 0; i < <c:out value="${GenericCodeForm.name}"/>_List.length; i++)
	<c:out value="${GenericCodeForm.name}"/>AutocompleteValues.push(<c:out value="${GenericCodeForm.name}"/>_List[i].name);
	
function set<c:out value="${GenericCodeForm.name}"/>(colorId, colorName) {
	colorId = colorId || null;
	colorName = colorName || "";
	if(colorId) {
		for(var i = 0; i < <c:out value="${GenericCodeForm.name}"/>_List.length; i++) {
			if(<c:out value="${GenericCodeForm.name}"/>_List[i].id == colorId) {
				$('#<c:out value="${GenericCodeForm.name}"/>Input').val(<c:out value="${GenericCodeForm.name}"/>_List[i].name);
				return true;
			}
		}
	}
	$('#<c:out value="${GenericCodeForm.name}"/>Input').val(colorName);
}

function submit<c:out value="${GenericCodeForm.name}"/>() {
	for(var i = 0; i < <c:out value="${GenericCodeForm.name}"/>_List.length; i++) {
		if(<c:out value="${GenericCodeForm.name}"/>_List[i].name == $('#<c:out value="${GenericCodeForm.name}"/>Input').val()) {
			$('#<c:out value="${GenericCodeForm.name}"/>Id').val(<c:out value="${GenericCodeForm.name}"/>_List[i].id);
			return true;
		}
	}
	$('#<c:out value="${GenericCodeForm.name}"/>Name').val($('#<c:out value="${GenericCodeForm.name}"/>Input').val());
}

recordmanager-ui/src/main/webapp/tiles/table.jsp
<%@ taglib uri="http://struts.apache.org/tags-logic" prefix="l" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib uri="http://www.deta.pro/deta.tld" prefix="deta" %>
<%@page import="ru.yar.vi.rm.UserHelper"%>
<%@page import="ru.yar.vi.rm.data.ActionDO"%>
<%@page errorPage="map.jsp" %>

<c:if test="${UserForm.actionId == 0}">
<%
	session.setAttribute("UserForm", session.getAttribute("UserForm0"));
%>
</c:if>
<jsp:useBean id="UserForm" class="ru.yar.vi.rm.user.form.UserForm" scope="session"/>


	
<l:notEqual name="UserForm" property="module" value="/self">
<p class="noprint"><c:out value="${deta:textToHtml(SITE.intro) }" escapeXml="false"/>
<%=UserHelper.makeHtml(UserForm.getSelectedAction().getDescription()) %></p>
</l:notEqual>
<p class="noprint"><%=UserHelper.makeHtml(UserForm.getSelectedAction().getWarningText()) %></p>

<table class="info noprint">

<c:if test="${! empty UserForm.name }">
<tr>
<td class="name">
<c:forEach items="${UserForm.fields }" var="item">
	<c:if test="${item.field eq 'name' }"><c:out value="${item.name }"/></c:if>
</c:forEach></td>
<td><c:out value="${UserForm.name }"/></td>
</tr>
</c:if>
<c:if test="${!UserForm.currentDay }">
<tr>
<td class="name"><fmt:message key='label.action'/></td>
<td><c:out value="${UserForm.selectedAction.name}"/></td>
</tr>
<c:if test="${UserForm.module ne '/self' }">
<tr>
<td class="name"><fmt:message key='label.region'/></td>
<td><c:out value="${UserForm.selectedRegion.name}"/></td>
</tr>
<c:if test="${UserForm.criteria >0 }">
<!-- <tr>
<td><c:forEach items="${UserForm.fields }" var="item">
	<c:if test="${item.field eq 'info(vehicleName)' }"><c:out value="${item.name }"/></c:if>
</c:forEach></td>
<td><c:out value="${UserForm.infoMap.vehicleName }"/>&nbsp;<c:out value="${UserForm.infoMap.vehicleNum }"/></td>
</tr>
-->
<c:forEach items="${UserForm.fields }" var="item">
	<c:if test="${item.field eq 'criteria' }">
		<jsp:useBean id="item" class="ru.yar.vi.rm.data.CustomFieldDO"/>
		<tr>
			<td class="name"><c:out value="${item.name }"/></td>
			<td><%=UserHelper.getName(UserForm.getCriteria(), item.getCriteria())%></td>
		</tr>
	</c:if>
</c:forEach>
<tr>
<td class="name"><fmt:message key='label.contact'/></td>
<td><c:out value="${UserForm.email }"/>&nbsp;<c:out value="${UserForm.phone }"/></td>
</tr>
</c:if></c:if></c:if>
</table>

<div class="print">
<pre>
<%=UserHelper.format(new java.util.Date())%>

<b><c:out value="${UserForm.name }"/></b><c:if test="${!UserForm.currentDay }">
<b><%=UserHelper.print(UserHelper.getName(UserForm.getActionId(), UserForm.getActions()))%></b>
<b><%=UserHelper.print(UserHelper.getName(UserForm.getCriteria(), UserForm.getCriterias()),UserHelper.LINE_LENGTH)%></b>
<b><c:out value="${UserForm.infoMap.vehicleName }"/> <c:out value="${UserForm.infoMap.vehicleNum }"/></b>
<b><c:out value="${UserForm.phone }"/></b></c:if>
</pre>
</div>